site_name: STIC - Portal de Proyectos y Documentación
site_url: http://192.168.67.10

nav:
- Home: 'index.md'
- Proyectos:
    - 'STIC Cloud': 'proyectos/cloud.md'
    - 'Data Warehouse': 'proyectos/dw.md'
    - 'Portal de transparencia': 'proyectos/transparencia.md'
- Recursos:
    - 'Tutoriales': 'recursos/tutoriales.md'
    - 'Formación': 'recursos/formacion.md'
    - 'Blog': 'recursos/blog.md'
    - 'Presentaciones': 'recursos/presentaciones.md'
    - 'Documentos': 'recursos/documentos.md'
- Noticias: 'noticias.md'
- Acerca de: 'about.md'

theme:
  name: 'material'
  font:
    text: 'Catamaran'
  logo: 'logo.png'
  favicon: 'img/favicon.ico'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ualmtorres'
    - type: 'twitter'
      link: 'https://twitter.com/ualmtorres'

repo_name: 'Repositorio del portal'
repo_url: 'https://github.com/ualmtorres/portalstic'

markdown_extensions:
  - admonition
