site_name: STIC - Portal de Proyectos y Documentación
site_url: http://192.168.67.10
nav:
- Home: 'index.md'
- Proyectos:
    - 'Portal STIC': 'proyectos/portal.md'
    - 'OpenStack STIC': 'proyectos/openstack.md'
    - 'Data Warehouse': 'proyectos/dw.md'
    - 'Portal de transparencia': 'proyectos/transparencia.md'
- Recursos:
    - 'Tutoriales': 'recursos/tutoriales.md'
    - 'Formación': 'recursos/formacion.md'
    - 'Blog': 'recursos/blog.md'
    - 'Presentaciones': 'recursos/presentaciones.md'
    - 'Documentos': 'recursos/documentos.md'
    - 'Instalaciones': 'recursos/instalaciones.md'
- Procedimientos:
    - 'Portal': 'procedimientos/portal.md'
    - 'Agiles': 'procedimientos/agiles.md'
    - 'Git': 'procedimientos/git.md'
    - 'APIs': 'procedimientos/api.md'
    - 'Estilo en documentos': 'procedimientos/estilodocs.md'
    - 'Estilo en aplicaciones': 'procedimientos/estiloapps.md'
    - 'Revisión de código': 'procedimientos/guiarevision.md'
    - 'Contribuciones': 'procedimientos/guiacontribucion.md'
    - 'Solicitudes de acceso': 'procedimientos/solicitudacceso.md'
    - 'Logging': 'procedimientos/logging.md'
    - 'Imágenes Docker': 'procedimientos/registrodocker.md'
    - 'Despliegues Kubernetes': 'procedimientos/kubernetes.md'
    - 'Monitorización': 'procedimientos/monitorizacion.md'
- Noticias: 'noticias.md'
- Acerca de: 'about.md'

theme:
  name: 'material'
  font:
    text: 'Catamaran'
  logo: 'logo.png'
  favicon: 'img/favicon.ico'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/ualmtorres'
    - type: 'twitter'
      link: 'https://twitter.com/ualmtorres'

markdown_extensions:
  - admonition
